spring:
  profiles:
     active: local
  jpa:
    properties:
      hibernate:
        format_sql: true
    show_sql: true
    hibernate:
      ddl-auto: validate

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

---

spring:
  datasource:
    url: jdbc:h2:~/test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
    username: sa
  config:
    activate:
      on-profile: local
  flyway:
    enabled: false

---

spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL;
    username: sa
  config:
    activate:
      on-profile: test
  jpa:
    hibernate:
      ddl-auto: create
  flyway:
    enabled: false
